services:
  db:
    image: postgres:15
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: medical_db  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistence des données
      - ./db/init:/docker-entrypoint-initdb.d # initialisation de la base de données
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d medical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: medical_mlflow
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=postgresql://user:password@db:5432/medical_db
    command: >
      mlflow server
      --backend-store-uri postgresql://user:password@db:5432/medical_db
      --registry-store-uri postgresql://user:password@db:5432/medical_db
      --default-artifact-root /mlartifacts
      --host 0.0.0.0
      --allowed-hosts "mlflow,mlflow:5000,localhost,localhost:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
    depends_on:
      db:
        condition: service_healthy
  
  api:
    build: 
      context: ./api
    container_name: medical_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./services:/app/services
      - ./data:/data
      - ./mlartifacts:/mlartifacts
    environment:
      - PYTHONPATH=/app:/app/services
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATABASE_URL=postgresql://user:password@db:5432/medical_db
    depends_on:
      - mlflow
      - db
      - ollama

  ollama:
    build:
      context: ./services/extraction
      dockerfile: Dockerfile
    container_name: medical_ollama
    runtime: nvidia # Utiliser le GPU si disponible
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_GPU=1


  train:
    build:
      context: .
      dockerfile: services/model_training/Dockerfile
    container_name: medical_train
    volumes:
      - ./data:/data
      - ./mlartifacts:/mlartifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_started
    profiles:
      - train

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    user: "472"

volumes:
  postgres_data:
  ollama_data:
  grafana_data:
  prometheus_data: