services:
  api:
    build: 
      context: ./api
    container_name: medical_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: medical_mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlartifacts --host 0.0.0.0
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlflow.db:/mlflow.db