services:
  db:
    image: postgres:15
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: medical_db  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistence des données
      - ./db/init:/docker-entrypoint-initdb.d # initialisation de la base de données
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d medical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: medical_mlflow
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=postgresql://user:password@db:5432/medical_db
    command: >
      mlflow server
      --backend-store-uri postgresql://user:password@db:5432/medical_db
      --default-artifact-root /mlartifacts
      --host 0.0.0.0
    volumes:
      - ./mlartifacts:/mlartifacts
    depends_on:
      db:
        condition: service_healthy
  
  api:
    build: 
      context: ./api
    container_name: medical_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATABASE_URL=postgresql://user:password@db:5432/medical_db
    depends_on:
      - mlflow
      - db

volumes:
  postgres_data: