{
 "title": "API monitoring",
 "time": { "from": "2026-03-13T09:57:39.023Z", "to": "2026-03-13T10:01:19.504Z" },
 "panels": [
  {
   "title": "Status API",
   "type": "stat",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"medical-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requêtes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requêtes par endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(endpoint) (api_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes/min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
   "targets": [
    { "expr": "rate(api_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence moyenne",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(api_request_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_request_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}